name: cherry-pick
on:
  pull_request:
    branches:
      - main
    types: ["closed"]


permissions:
  issues: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.number }}

jobs:

  cherry_pick_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["1.0", "1.1", "2.0"]
    name: Cherry pick
    steps:
      - name: Dump GitHub labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: echo "$LABELS"


      - name: Checkout
        if: contains(github.event.pull_request.labels.*.name, 'cherry-pick on merge into ${{ matrix.tag }}') && github.event.pull_request.merged == true
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: cherry
        if: contains(github.event.pull_request.labels.*.name, 'cherry-pick on merge into ${{ matrix.tag }}') && github.event.pull_request.merged == true
        run: |
            ./.github/scripts/cherry-pick.sh
        env:
          TARGET_BRANCH: release/${{ matrix.tag }}


