name: ci
on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - run: |
            branch_name=${GITHUB_REF##*/}
            if [[ "$branch_name" == "master" ]]; then
                export TARGET="latest"
            else
                version=${branch_name#release/}
                major_version=${version%%.*}
                export TARGET="${major_version}.x"
            fi
            make docs-publish
