name: ci
on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            git config user.name $GITHUB_ACTOR
            git config user.email $GITHUB_ACTOR@users.noreply.github.com
            make install


      - name: run
        run: |
            branch_name=${GITHUB_REF##*/}
            if [[ "$branch_name" == "master" ]]; then
                export TARGET="latest"
            else
                version=${branch_name#release/}
                major_version=${version%%.*}
                export TARGET="${major_version}.x"
            fi
            make docs-publish
